### ISSUE TITLE
core: memory leak leads to zdbfs killed by kernel oom

### ISSUE THREAD

**Issue by LeeSmet** [threefoldtech/0-db-fs#26]
On the pecs IT VM, the process was OOMed after reaching about 28GB of memory

![image](https://user-images.githubusercontent.com/22023708/131470229-a45fcde9-a3ae-4695-b0b0-30032949b27d.png)

**Comment by LeeSmet** [comment]
This issue occured again a couple of times. Last time there were absolutely no errors in other components. As an additional note, it happened after about 2 hours of writing small objects at 11ish MB/s. See following screenshot from grafana (from 0-db-fs stats) for some more context:

![image](https://user-images.githubusercontent.com/22023708/132305159-b478f99c-d202-48ed-bd1e-204b788cdff7.png)

It seems cache is never flushed? I have seen cache flushes before, so the dashboard is working. Also the other metrics are properly shown, so the tool collecting 0-db-fs stats was working properly

**Comment by maxux** [comment]
Do we have memory usage chart aswell ? When did OOM occured ?
From what I see here, there were lot of write then no more write and some readdir calls. I wonder if memory was still growing after ~16h50

**Comment by maxux** [comment]
This sound like issue when zdb payload size limitation is reached, which occurs on large directory. This is related to #16 because of directory size (inode size).

**Comment by maxux** [comment]
Memory leak confirmed.
```
[.] cache: inode cache expired: 2, flushing
[+] zdb: zdbfs-meta: set: update id: 2, 8555826 bytes
[-] zdb: zdbfs-meta: set: id 2: Connection reset by peer
[-] zdbfs: store inode: failed
[-] cache: could not write inode in the backend
```

After that point, memory keep growing. This is related to #14, there is no segmentation fault but zdb response is not handled correctly.

Actually what happen is: metadata (directory) is larger than 8 MB, which is rejected by `zdb`, when this happen, `zdb` drop the connection instantly. The connection is never established again and whatever, the inode won't never be saved because it's too large.
